# Generated by Django 4.1.2 on 2023-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_files_gallery_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
